### ISSUE TITLE
Review existing unit tests 

### ISSUE THREAD

**Issue by avllee21** [nyu-devops-summer-2021-inventory/inventories#11]
**As a** developer
**I need** unit tests for the code in the repository
**So that** there will be less mistakes during development

**Assumptions**
* There will be TDD files that will contain the unit tests for the features

**Acceptance criteria**
```
Standard PyUnit syntax is followed in the tests.
Use the coverage tool to measure test coverage. Get coverage of at least 95%
```

**Comment by cslecrone** [comment]
I'm interested in John's take on this. It should be everyone's responsibility to write tests that cover any new functionality that's introduced to the application rather than the responsibility of a single person.

**Comment by avllee21** [comment]
Perhaps I can modify this story from "Write unit tests for the code" to "Review existing unit tests for each feature"? 

So other developers can also make sure that unit tests provide sufficient coverage or they can suggest improvements to the existing unit tests as well.

**Comment by cslecrone** [comment]
I think the difficulty there is that this ends up being a task that's dependent on a bunch of other tasks. However, I still think it's probably worth checking with John! I think we still need 4-5 additional stories for the other endpoints in the application, that may be a good place to make some additional stories.
