### ISSUE TITLE
Create a Burndown chart 

### ISSUE THREAD

**Issue by avllee21** [nyu-devops-summer-2021-inventory/inventories#13]
**As a** team member
**I need** a burndown chart
**So that** the entire team can see and track the progress of this project

**Assumptions**
* Zenhub can be used in the creation of the burndown chart

**Acceptance criteria**
```
The burndown chart clearly shows the progress of the team. 
```

**Comment by cslecrone** [comment]
I _think_ this is just built in to ZenHub, and shouldn't require any additional work:

https://help.zenhub.com/support/solutions/articles/43000010356-track-sprint-progress-with-burndown-charts

**Comment by avllee21** [comment]
Oops, I did not know that. I edited the story estimate from 3 to 1 and mentioned that Zenhub can be used in the assumptions.

**Comment by Imsiaocong** [comment]
Thoughts before closing this issue?

**Comment by cslecrone** [comment]
If you have a link to the burndown chart, can you share it in Slack and as a comment in the issue? If not, let's leave it open.

**Comment by cslecrone** [comment]
I was able to create the burndown chart with just a couple of clicks (you can view it via Reports -> Burndown Report -> Milestones). 

![image](https://user-images.githubusercontent.com/11970801/123562892-77766b80-d77f-11eb-8902-41500e9938a5.png)
