### ISSUE TITLE
Configure PyLint

### ISSUE THREAD

**Issue by cslecrone** [nyu-devops-summer-2021-inventory/inventories#14]
**As a** developer
**I need** automatic feedback on the style and formatting of my code
**So that** my code is stylistically consistent with the rest of my team and the language community as a whole

**Assumptions**
* We will configure PyLint to ensure our code confirms to PEP8
* PyLint will run automatically when Pull Requests are opened

**Acceptance criteria**
* All Pull Requests have PyLint executed against them and will notify developers of any violations

**Comment by cslecrone** [comment]
Just as an FYI, `pylint` and `flake8` are already defined in our `requirements.txt` so VS Code should be able to detect them if the correct interpreter is selected. We may not need to do anything here.

**Comment by Imsiaocong** [comment]
> Just as an FYI, `pylint` and `flake8` are already defined in our `requirements.txt` so VS Code should be able to detect them if the correct interpreter is selected. We may not need to do anything here.

Does this mean if I git pull the latest files and do 'vagrant up -> vagrant ssh', what's inside the requirement.txt will automatically be installed by the system?

**Comment by cslecrone** [comment]
Correct.

**Comment by cslecrone** [comment]
I confirmed that PyLint is installed and can be selected using `"Python: Select Linter"` from within VS Code's command pallet.
