### ISSUE TITLE
Create Models for the Inventory service

### ISSUE THREAD

**Issue by cslecrone** [nyu-devops-summer-2021-inventory/inventories#15]
**As a** developer
**I need** models to provide abstractions about the data required for requests to and responses from my service as well as storage in the database
**So that** inputs to and outputs from the service can be structured and consistent

**Assumptions**
* Models will be contained in a `models.py`
* Models need to understand all of the data related to our inventory
* Models need methods to perform serialization/de-serialization
* Models need methods to list all database entries

**Acceptance criteria**
* `models.py` contains all required models for our service
* `test_models.py` contains tests for all models

**Comment by Imsiaocong** [comment]
Just curious, what is the equivalent file to the test_model.py in lab-flask-tdd?

**Comment by cslecrone** [comment]
test_pets.py

**Comment by Imsiaocong** [comment]
Hi Cam, I am adding update function to the model.py because it is needed for the PUT action.

**Comment by cslecrone** [comment]
Yep! That's the idea. I just wanted to get the base implemented, people will need to add quite a bit more functionality to the service.
