### ISSUE TITLE
Add an ACTION endpoint to the service

### ISSUE THREAD

**Issue by avllee21** [nyu-devops-summer-2021-inventory/inventories#20]
**As a** website administrator
**I need** API endpoints to update whether an item is in stock or out of stock
**So that** we can keep customers informed about the availability of items

**Assumptions**
* We'll need two endpoints `/inventories/<ID>/in-stock` and `/inventories/<ID>/out-of-stock` that accept `PUT` requests
* Successful requests will return `204`
* Failed requests will return appropriate return codes based on the error type

**Acceptance criteria**
* A successful `PUT` to `/inventories/<ID>/in-stock` will update the `in_stock` attribute of our `Inventory` model to `True`
* A successful `PUT` to `/inventories/<ID>/out-of-stock` will update the `in_stock` attribute of our `Inventory` model to `False`

**Comment by Imsiaocong** [comment]
Ay let me try it
