### ISSUE TITLE
Create a Vagrantfile

### ISSUE THREAD

**Issue by cslecrone** [nyu-devops-summer-2021-inventory/inventories#3]
**As a** developer
**I need** an idempotent development environment consistent with the rest of my team
**So that** as I develop, I can have confidence that if it "works on my machine" it will work elsewhere

**Assumptions**
* We will use `Vagrant` to define our portable development environment
* Our development environment will require `python3` and `postgres`
* We will use Ubuntu Linux as the operating system
* We will need to install `flask` and some additional dependencies using `pip` 

**Acceptance criteria**
* The Vagrant environment contains all software required for the project, through the use of Dockerized software
* Developers only have to run `vagrant up` and `vagrant ssh` to start developing

**Comment by avllee21** [comment]
Additionally, we want to use Docker inside of our Vagrant VM for any 3rd party services that we want to use. So the Vagrant VM will contain all software required for the project through the use of Docker containers.

**Comment by cslecrone** [comment]
Yep! `The Vagrant environment contains all software required for the project` would include any of the Dockerized software required to run the app (like a database or a caching layer).
