### ISSUE TITLE
Create a README.md

### ISSUE THREAD

**Issue by cslecrone** [nyu-devops-summer-2021-inventory/inventories#4]
**As a** developer
**I need** a README file
**So that** I understand which calls are available to the Inventory microservice, what parameters those calls require, how to run the service and how to test the service to ensure it's working properly. 

**Assumptions**
* The `README` will be written in markdown so it's formatted nicely and easy to read in GitHub

**Acceptance criteria**
* The `README` contains all available calls to the microservice and the required inputs 
* The `README` contains instructions on how to start the service
* The `README` contains instructions on how to execute tests for the service

**Comment by Imsiaocong** [comment]
Hi,
I am having trouble coming up with: 
"The README contains all available calls to the microservice and the required inputs"

- What are the available calls?
- What are the required inputs

**Comment by Imsiaocong** [comment]
Please update readme.md along the process folks.
