### ISSUE TITLE
Add Swagger Docs

### ISSUE THREAD

**Issue by Imsiaocong** [nyu-devops-summer-2021-inventory/inventories#50]
**As a developer**
- I need to have swagger docs implemented
- So that it allows us to describe the structure of ourr APIs so that machines can read them. The ability of APIs to describe their own structure is the root of all awesomeness in Swagger. By reading our API's structure, we can automatically build beautiful and interactive API documentation.

**Assumptions**
- Add Swagger annotations to our service to document our REST API using Flask-RESTX as shown in class. 
The documentation API must be available at: /apidocs/
- Add Swagger data models to document our API payloads
- Ensure that our Swagger docs work correctly and specify our data model so that others know what to send to our API 

**Acceptance criteria**
- A good use of Flask-RESTX annotations and that the same test cases should still work as expected. A working and accurate Swagger docs is expected.

**Comment by cslecrone** [comment]
I broke this down by API endpoint, so I'm closing the original ticket.
