### ISSUE TITLE
Add a BDD Scenario for Create

### ISSUE THREAD

**Issue by JackieWang1201** [nyu-devops-summer-2021-inventory/inventories#51]
**As a** developer
**I need** a BDD Scenario for Create
**So that** I can implement BDD testing for Create

**Assumptions**

* Write at least one Scenario for Create in `.feature` file
* Write the feature using `Gherkin` syntax that is understood by the
  behave tool

**Acceptance criteria**

```
Given I have no items in my inventory

When I create an inventory item with the SKU ABC123

Then I should have 1 item in my inventory, and it should have the SKU ABC123
```

**Comment by cslecrone** [comment]
Missing story content?
