### ISSUE TITLE
Add a BDD Scenario for Read

### ISSUE THREAD

**Issue by JackieWang1201** [nyu-devops-summer-2021-inventory/inventories#52]
**As a** developer
**I need** a BDD Scenario for Read
**So that** I can implement BDD testing for Read

**Assumptions**

* Write at least one Scenario for Read in `.feature` file
* Write the feature using `Gherkin` syntax that is understood by the
  behave tool

**Acceptance criteria**

```
Given I have 3 items in my database

When I ask for the item with ID 1

Then I'm returned 1 item, and it has ID 1
```

**Comment by cslecrone** [comment]
Missing story content?
