### ISSUE TITLE
Add a BDD Scenario for Update

### ISSUE THREAD

**Issue by JackieWang1201** [nyu-devops-summer-2021-inventory/inventories#53]
**As a** developer
**I need** a BDD Scenario for Update
**So that** I can implement BDD testing for Update

**Assumptions**

* Write at least one Scenario for Update in `.feature` file
* Write the feature using `Gherkin` syntax that is understood by the
  behave tool

**Acceptance criteria**

```
Given I have 1 item with my inventory with a SKU of ABC123 and a count of 10

When somebody purchases one of ABC123

Then I should still only have 1 item in my inventory, but it should have a count of 9

**Comment by cslecrone** [comment]
Story content?
