### ISSUE TITLE
Add BDD Scenario for in-stock Action

### ISSUE THREAD

**Issue by JackieWang1201** [nyu-devops-summer-2021-inventory/inventories#57]
**As a** developer
**I need** BDD Scenarios for out-of-stock/in-stock Actions
**So that** I can implement BDD testing for out-of-stock/in-stock Actions
**Assumptions**

* Write at least one Scenario for out-of-stock/in-stock Actions in `.feature` file
* Write the feature using `Gherkin` syntax that is understood by the
  behave tool

**Acceptance criteria**

```
Given I have 1 item in my inventory and it is out of stock

When I toggle the item to in_stock

Then I should see the item and users should be notified via email that the item is in stock again

**Comment by cslecrone** [comment]
We only have an in-stock action right now, so I've updated the description.
